# Generated by Django 5.0.2 on 2024-02-21 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('total_price', models.FloatField(default=0)),
                ('delivery_address', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=13)),
                ('payment_type', models.IntegerField(choices=[(1, 'CASH'), (2, 'PAYME'), (3, 'CLICK')], default=1)),
                ('payed', models.FloatField(default=0)),
                ('status', models.IntegerField(choices=[(0, 'CANCELED'), (1, 'PENDING'), (2, 'IN PROCESS'), (3, 'DELIVERED')], default=1)),
                ('comment', models.CharField(max_length=200)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
