# Generated by Django 5.0.2 on 2024-02-21 08:03

import store.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone_number',
            field=models.CharField(max_length=13, validators=[store.validators.validate_uz_phone_number]),
        ),
    ]
