from django.urls import path
from .views import (
    home_view,
    men_products_view,
    women_products_view,
    baby_products_view,
    product_detail_view,
    cart_view,
    checkout_view,
    cart_obj_view,
    like_obj_view,
    update_cart_view,
    delete_cart_view,
    wishlist_view,
    pay_online_view,
    delete_order_view,
    add_card_view,
    add_card_details_view,
    exit_card_view,
    about_view,
    faq_view,
    support_view,
    privacy_view,
    search_view,
)

urlpatterns = [
    path('', home_view),
    path('men_products/', men_products_view),
    path('women_products/', women_products_view),
    path('baby_products/', baby_products_view),
    path('product_detail/<int:pk>', product_detail_view),
    path('cart_add/', cart_view),
    path('update_cart/', update_cart_view),
    path('delete_cart/<int:pk>/', delete_cart_view),
    path('delete_order/<int:pk>/', delete_order_view),

    path('checkout/', checkout_view, name='checkout'),
    path('wishlist/', wishlist_view, name='wishlist'),
    path('cart/', cart_obj_view),
    path('like/', like_obj_view),
    path('pay_online/<int:pk>/', pay_online_view, name='pay_online'),

    path('add_card/', add_card_view, name='add_card'),
    path('add_card_details/', add_card_details_view, name='add_card_details'),
    path('exit_card/<int:pk>/', exit_card_view, name='exit_card'),
    path('support/', support_view, name='support_view'),
    path('faq/', faq_view, name='faq_view'),
    path('privacy/', privacy_view, name='privacy_view'),
    path('about/', about_view, name='about_view'),
    path('search/', search_view, name='search'),
]
